export const CIDADES = [
  "São Paulo",
  "Rio de Janeiro",
  "Belo Horizonte",
  "Curitiba",
  "Porto Alegre",
  "Brasília",
  "Salvador",
  "Fortaleza",
  "Recife",
  "Manaus",
  "Goiânia",
  "Belém",
  "Campinas",
  "Guarulhos",
  "São Bernardo do Campo",
  "Santo André",
  "Osasco",
  "Ribeirão Preto",
  "Sorocaba",
  "Uberlândia",
  "Florianópolis",
  "Vitória",
  "Natal",
  "João Pessoa",
  "Maceió"
].sort();
